name: grades
description: Made for students, by students. The unofficial grades app for the school district of Palm Beach County. View your grades at a glance.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 1st party packages
  grade_core:
    path: vendored/grade_core

  shared_preferences: ^0.5.6+3
  # General small unities
  # Dart team package
  intl: ^0.16.1
  # Dart team package
  collection: ^1.14.11
  pedantic: ^1.9.0

  quiver: ^2.1.3
  tuple: ^1.0.3

  # Fonts and Icons
  font_awesome_flutter: ^8.8.1

  equatable: ^1.1.1

  bloc: ^3.0.0

  flutter_bloc: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  tuple:
    git:
      url: https://github.com/SwiftGrade/tuple
      ref: master

  # Fonts and Icons
  font_awesome_flutter:
    git:
      url: https://github.com/SwiftGrade/font_awesome_flutter
      ref: master

  equatable:
    git:
      url: https://github.com/SwiftGrade/equatable
      ref: master

  bloc:
    git:
      url: https://github.com/SwiftGrade/bloc
      ref: bloc-v3.0.0
      path: packages/bloc

  flutter_bloc:
    git:
      url: https://github.com/SwiftGrade/bloc
      ref: flutter_bloc-v3.2.0
      path: packages/flutter_bloc

  nested:
    git:
      url: https://github.com/SwiftGrade/nested
      ref: master

  provider:
    git:
      url: https://github.com/SwiftGrade/provider
      ref: master

  quiver:
    git:
      url: https://github.com/SwiftGrade/quiver-dart
      ref: master