name: grades
description: The grades app for the School District of Palm Beach County. View your grades at a glance.
author: GoldinGuy, Noskcaj
version: 3.0.16+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 1st party packages
  grade_core:
    path: vendored/grade_core

  shared_preferences: ^2.0.5
  # General small unities
  # Dart team package
  intl: ^0.17.0
  # Dart team package
  collection: ^1.15.0
  pedantic: ^1.11.0

  quiver: ^3.0.1
  tuple: ^2.0.0
  built_collection: ^5.0.0

  onesignal_flutter: ^2.6.3

  http: ^0.13.3

  flutter_picker:
    git: git://github.com/SwiftGrade/flutter_picker.git

  # Fonts and Icons
  font_awesome_flutter: ^9.0.0

  equatable: ^2.0.0

  bloc: ^7.0.0

  flutter_bloc: ^7.0.0

  flutter_circular_chart_two:
    git: https://github.com/jcsena/flutter_circular_chart

  url_launcher: ^6.0.3

  webview_flutter: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
