name: grade_core
description: The BLoC core SwiftGrade is built on top of.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  pedantic: ^1.9.0
  meta: ^1.1.8

  sentry: ^3.0.1
  package_info: ^0.4.0+16

  sis_loader:
    path: ../sis-loader

  shared_preferences: ^0.5.6+3
  flutter_secure_storage: ^3.3.2

  equatable: ^1.1.1
  bloc: ^4.0.0
  tuple: ^1.0.3

  built_value: ^7.1.0
  built_collection: ^4.3.2

dev_dependencies:
  test: ^1.14.2
  mockito: ^4.1.1

  bloc_test: ^5.0.0
  flutter_test:
    sdk: flutter

  build_runner: ^1.9.0
  built_value_generator: ^7.1.0


dependency_overrides:
  flutter_secure_storage:
    git:
      url: https://github.com/SwiftGrade/flutter_secure_storage
      ref: develop