name: sis_loader
description: A library to fetch grades from sis

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4
  client_cookie: ^2.2.1
  intl: ^0.16.1
  equatable: ^1.1.1


dev_dependencies:
  test: ^1.14.2
  pedantic: ^1.9.0

dependency_overrides:
  equatable:
    git:
      url: https://github.com/SwiftGrade/equatable
      ref: master
