name: grades
description: Made for students, by students. The unofficial grades app for the school district of Palm Beach County. View your grades at a glance.

version: 1.0.1+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  # Core flutter
  flutter:
    sdk: flutter

  # 1st party packages
  sis_loader:
    git: https://github.com/Noskcaj19/dart-sis-loader.git

  # Debug/Error reporting/System packages
  sentry: ^3.0.1
  package_info: ^0.4.0+13

  # "Framework" utilities
  provider: 4.0.1
  shared_preferences: ^0.5.6+1

  # General small unities
  intl: ^0.16.1

  # Fonts and Icons
  font_awesome_flutter: ^8.5.0

  # General UI
  flutter_spinkit: ^4.1.1+1
  flutter_circular_chart: ^0.1.0
  rflutter_alert:
    git: git://github.com/RatelHub/rflutter_alert.git

dev_dependencies:
  flutter_launcher_icons: ^0.7.4

  flutter_test:
    sdk: flutter

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/icon.png"
flutter_icons:
  android: true
  ios: true
  image_path_android: assets/icon/ic_launcher_xxxhdpi.png
  image_path_ios: assets/icon/ios.png
  adaptive_icon_background: assets/icon/ic_background.png
  adaptive_icon_foreground: assets/icon/ic_foreground.png

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
