name: grades
description: Made for students, by students. The unofficial grades app for the school district of Palm Beach County. View your grades at a glance.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 1st party packages
  grade_core:
    path: vendored/grade_core

  shared_preferences: ^0.5.6+3
  # General small unities
  # Dart team package
  intl: ^0.16.1
  # Dart team package
  collection: ^1.14.11
  pedantic: ^1.9.0

  tuple:
    git:
      url: https://github.com/Noskcaj19/tuple
      ref: d39ed10

  # Fonts and Icons
  font_awesome_flutter:
    git:
      url: https://github.com/Noskcaj19/font_awesome_flutter.git
      ref: 16cba90

  equatable: ^1.1.1
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
