name: grades
description: Made for students, by students. The unofficial grades app for the school district of Palm Beach County. View your grades at a glance.

version: 3.0.9+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 1st party packages
  grade_core:
    path: vendored/grade_core

  shared_preferences: ^0.5.8
  # General small unities
  # Dart team package
  intl: ^0.16.1
  # Dart team package
  collection: ^1.14.13
  pedantic: ^1.9.2

  quiver: ^2.1.3
  tuple: ^1.0.3
  built_collection: ^4.3.2

  # Fonts and Icons
  font_awesome_flutter: ^8.8.1

  equatable: ^1.2.3

  bloc: ^6.0.1

  flutter_bloc: ^6.0.1

  flutter_circular_chart: ^0.1.0

  url_launcher: ^5.5.0

  webview_flutter: ^0.3.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_secure_storage:
    git:
      url: https://github.com/SwiftGrade/flutter_secure_storage
      ref: develop
