name: grade_core
description: The BLoC core SwiftGrade is built on top of.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  pedantic: ^1.9.0
  meta: ^1.1.8

  sis_loader:
    path: ../sis-loader

  shared_preferences: ^0.5.6+3

  equatable: ^1.1.1
  bloc: ^3.0.0
  tuple: ^1.0.3

dev_dependencies:
  test: ^1.14.2
  mockito: ^4.1.1

  bloc_test: ^4.0.0
  flutter_test:
    sdk: flutter


dependency_overrides:
  tuple:
    git:
      url: https://github.com/Noskcaj19/tuple
      ref: master

  bloc_test:
    git:
      url: https://github.com/SwiftGrade/bloc
      path: packages/bloc_test
      ref: bloc-v3.0.0

  bloc:
    git:
      url: https://github.com/SwiftGrade/bloc
      path: packages/bloc
      ref: bloc-v3.0.0

  equatable:
    git:
      url: https://github.com/SwiftGrade/equatable
      ref: master
