name: grade_core
description: The BLoC core SwiftGrade is built on top of.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  pedantic: ^1.11.0
  meta: ^1.3.0

  sentry: ^5.0.0
  package_info: ^2.0.0

  sis_loader:
    path: ../sis-loader

  shared_preferences: ^2.0.5
  flutter_secure_storage: ^4.2.0

  equatable: ^2.0.3
  bloc: ^7.0.0
  tuple: ^2.0.0

  built_value: ^8.1.2
  built_collection: ^5.1.0

dev_dependencies:
#  test: ^1.17.4
  mockito: ^5.0.7

  bloc_test: ^8.0.0
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.1
  built_value_generator: ^8.0.6